### ISSUE TITLE
The app opens (PID visible) but the window / pane doesn't

### ISSUE THREAD

**Issue by nicolasembleton** [connor-finlay/mactop#2]
I'm not exactly sure why but the app opens for me, however I see no pane / window opening. I got it from the AppStore. What info should I provide? Has anyone had that issue? I'm on 14.6.1 (23G93), Macbook Pro M2 MAX 64G.

**Comment by connor-finlay** [comment]
Hi,

Is the icon visible in your menu bar at the top? 

If it’s not, can I ask if you have quite a lot of apps in the menu bar? Mac OS will decide after X number of apps not to show another menu bar app. Please try closing some if so.

**Comment by nicolasembleton** [comment]
Good catch... Did not think of that. It shows now 😅 Thanks.
